### ISSUE TITLE
Opnsense App for Splunk install seems incomplete

### ISSUE THREAD

**Issue by RutgerDiehard** [ZachChristensen28/Opnsense_App_for_Splunk#62]
### Bug description

I have a working Splunk Enterprise install, Splunk Universal Forwarder and rsyslog configured using the instructions on [App/TA](https://splunk-opnsense.ztsplunker.com) website. I can see logs from OPNsense within Splunk for each index. Opnsense_TA_for_splunk, Splunk CIM and Opnsense_App_for_Splunk are installed. However, when I launch the Opnsense_App_for_splunk App, there is no data in any of the Default Views (any of the dashboard views) and there are no macros listed in Opnsense_App_for_Splunk->Advanced Search->Macros (App=Opnsense_App_for_Splunk, Configuration Source=Created in App, Owner=Any).

It seems there is configuration missing. I can't recreate the macros from the macro reference as the arguments for each macro  are missing in the documentation. Or maybe I'm just not understanding what to expect from the TA and App for Opnsense data via Splunk.

EDIT: I have created the missing macros and used the arguments listed between the $...$ for each macro. However, the dashboards are still blank.

### Related links

- [Example Issue](https://splunk-opnsense.ztsplunker.com/landing-page/)
-

### OPNsense App for Splunk Version (This App)

1.1.4

### TA-opnsense Version

1.5.4

### Splunk Version

9.2.1

### OPNsense Version

24.1.6

**Comment by RutgerDiehard** [comment]
Resolved.

Let's just say it was my lack of understanding that was the issue.

**Comment by ZachChristensen28** [comment]
Make sure that you have the CIM add-on installed. https://splunkbase.splunk.com/app/1621On Sep 12, 2024, at 11:07 AM, StarkZarn ***@***.***> wrote:﻿
@RutgerDiehard
I am running into a similar issue right now, my dashboards show Error in 'DataModelEvaluator': Data model 'Network_Traffic' was not found. or whatever data model matches the dashboard.
I'm just learning Splunk right now as well. Any tips?
